#!/bin/sh

#:Test ZPT

# Initialize
# ----------
. $srcdir/t.config
DIR=t-0118_out
rm -rf $DIR
mkdir $DIR
cd $DIR


# Run the test
# ------------

for f in 2 5 9 25 67 125 256 ; do
    zpt -Q -r 2 -c 3 x$f ${DATA}/Mat$f - ${DATA}/Mat$f - ${DATA}/Mat$f -
done
../checksum x2 444.3704327886 || exit 1
../checksum x5 1164.731234515 || exit 1
../checksum x9 1740.376812746 || exit 1
../checksum x25 3468.1636862360 || exit 1
../checksum x125 3468.713144823 || exit 1
../checksum x67 3468.3032512822 || exit 1
../checksum x256 3468.3805289708 || exit 1

zpt x ${DATA}/Perm1 ${DATA}/Perm2
zpt y x ${DATA}/Perm1
../checksum x 172.2962610961 || exit 1
../checksum y 252.3860806406 || exit 1
