#!/bin/sh

#:Test ZSY
# --------

# Initialize
# ----------
. $srcdir/t.config
DIR=t-0113_out
rm -rf $DIR
mkdir $DIR
cd $DIR


# Run the test
# ------------
zsy -Q e2 ${DATA}/Perm1 x1
zsy -Q e3 ${DATA}/Perm1 x2
../checksum x1 772.2115894062  || exit 1
../checksum x2 4572.2159097617 || exit 1


zct 1-5:1-7 ${DATA}/Mat67 m67
zct 1-5:1-6 ${DATA}/Mat25 m25
zct 1-7:1-7 ${DATA}/Mat9 m9
zsy -Q e2 ${DATA}/Mat5 x1
zsy -Q e3 m67 x2
zsy -Q e4 m25 x3
zsy -Q s2 ${DATA}/Mat2 x4
../checksum x1 25404.3020209772 || exit 1
../checksum x2 362.1554181026 || exit 1
../checksum x3 87.4019966339  || exit 1
../checksum x4 11412.1035840264 || exit 1
