#!/bin/sh

#:Test ZPR -G
# -----------

# Initialize
# ----------
. $srcdir/t.config
DIR=t-0116_out
rm -rf $DIR
mkdir $DIR
cd $DIR


# Run the test
# ------------

zpr -G ${DATA}/Perm1 p1
zpr -G ${DATA}/Perm2 p2
../checksum p1 89.1843631757 || exit 1
../checksum p2 89.844334804 || exit 1

zpr -G ${DATA}/Mat2 x2
zpr -G ${DATA}/Mat25 x25
zpr -G ${DATA}/Mat67 x67
../checksum x2 1251.4048248722 || exit 1
../checksum x25 5111.3837421290 || exit 1
../checksum x67 1578.4086279539 || exit 1
