#!/bin/sh

#:Test ZCP
# --------

# Initialize
# ----------
. $srcdir/t.config
DIR=t-0114_out
rm -rf $DIR
mkdir $DIR
cd $DIR


# Run the test
# ------------
zcp ${DATA}/ac.1 > zcp.log || error "ZCP failed"
zcp -f ${DATA}/ac.1 >> zcp.log || error "ZCP failed"
zcp -G ${DATA}/ac.1 >> zcp.log || error "ZCP failed"
zcp ${DATA}/ac.2 >> zcp.log || error "ZCP failed"
zcp -f ${DATA}/ac.2 >> zcp.log || error "ZCP failed"
zcp -G ${DATA}/ac.2 >> zcp.log || error "ZCP failed"
../checksum zcp.log 4399.265798641 || exit 1
