#!/bin/sh

#:Test ZTR.
# ---------
#

# Initialize
# ----------
. $srcdir/t.config
DIR=t-0107_out
rm -rf $DIR
mkdir $DIR
cd $DIR

# Run the test
# ------------
ztr ${DATA}/Mat2 x2
ztr ${DATA}/Mat5 x5
ztr ${DATA}/Mat25 x25
ztr ${DATA}/Mat67 x67
ztr ${DATA}/ac.1 ac

../checksum x2 84.1963892729 || exit 1
../checksum x5 204.3745149098 || exit 1
../checksum x25 588.499337148 || exit 1
../checksum x67 588.2460095492 || exit 1
../checksum ac 5690.872810896 || exit 1
