#!/bin/sh

#:Test ZMO.
# ---------
#
# Run ZMO on two permutations with different seed points.
#

# Initialize
# ----------
. $srcdir/t.config
cd t-0109_out


# Run the test
# ------------

cp ${DATA}/Perm1 x.1
cp ${DATA}/Perm2 x.2
zmo -Q x orb1
zmo -s 2 -Q x orb2
zmo -s 5 -Q x orb5
zmo -s 12 -Q x orb12
../checksum orb1 140.3351884555 || exit 1
../checksum orb2 140.3351884555 || exit 1
../checksum orb5 140.3351884555 || exit 1
../checksum orb12 140.3993436787 || exit 1

